In [3]:
from bs4 import BeautifulSoup

In [4]:
import requests

In [5]:
response=requests.get(url="https://realpython.com/")

In [6]:
print(response.text)

<!doctype html>
<html lang="en">
  <head>


    <link href="https://files.realpython.com" rel="preconnect">

    <title>Python Tutorials – Real Python</title>
    <meta name="author" content="Real Python">
    <meta name="description" content="Learn Python online: Python tutorials for developers of all skill levels, Python books and courses, Python news, code examples, articles, and more.">
    <meta name="keywords" content="">



    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no, viewport-fit=cover">


      <link rel="stylesheet" href="/static/realpython.min.3107e3a57ed2.css">
      <link rel="stylesheet" href="/static/gfonts/font.5ac42994de49.css">
      <link rel="preload" href="/static/glightbox.min.9b438b29cef1.css" as="style" onload="this.onload=null;this.rel='stylesheet'"><noscript><link rel="stylesheet" href="/static/glightbox.min.9b438b29cef1.css"></noscript>







      <link rel="canonical" href="https://realpython.com/">





<meta name="twitter:card" content="summary">
<meta property="twitter:image" content="https://realpython.com/static/social-default-image.5e1aa4786b3a.png">
<meta property="og:image" content="https://realpython.com/static/social-default-image.5e1aa4786b3a.png">


      <meta name="twitter:creator" content="@realpython">
      <meta name="twitter:site" content="@realpython">
      <meta property="og:title" content="Python Tutorials – Real Python">
      <meta property="og:type" content="website">
      <meta property="og:url" content="https://realpython.com/">
      <meta property="og:description" content="Learn Python online: Python tutorials for developers of all skill levels, Python books and courses, Python news, code examples, articles, and more.">


    <link href="/static/favicon.68cbf4197b0c.png" rel="icon">
    <link href="https://realpython.com/atom.xml" rel="alternate" title="Real Python" type="application/atom+xml">
    <link rel="manifest" href="/manifest.json">







    <script id="icons-data" type="application/json">{"iconsUrl": "/static/icons.6eec2e95bede.svg"}</script>
    <script id="optins-data" type="application/json">{"turnstileSiteKey": "0x4AAAAAAAQQUCLRXBi8NnUh"}</script>



<script async src="https://www.googletagmanager.com/gtag/js?id=G-L7L6L5F6Y6"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'G-L7L6L5F6Y6');



  gtag('get', 'G-L7L6L5F6Y6', 'client_id', (clid) => {
    document.cookie = 'gaclid=' + clid + ';max-age=86400000;path=/;secure';
  });

</script>

  </head>
  <body >



<nav class="navbar fixed-top navbar-expand-lg navbar-dark flex-column  user-select-none">
  <div class="container flex-row">

    <a class="navbar-brand" href="/">
      <img src="/static/real-python-logo.893c30edea53.svg" width="165" height="40" class="d-inline-block align-top" alt="Real Python">
    </a>


    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse navbar-nav-scroll" id="navbarSupportedContent" role="navigation" aria-label="Main Navigation">

      <ul class="navbar-nav mr-2">

        <li class="nav-item">
          <a class="nav-link rounded" href="/start-here/">Start&nbsp;Here</a>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link rounded dropdown-toggle" href="#" id="navbarDropdownLibrary" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="icon baseline" aria-hidden="true"><svg aria-hidden="true"><use href="/static/icons.6eec2e95bede.svg#brands--python"/></svg></span> Learn Python
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownLibrary">

<a class="dropdown-item " href="/search?kind=article&kind=course&order=newest" style="color: #ff7e73; line-height: 110%;"><span class="icon baseline mr-1" aria-hidden="true"><svg aria-hidden="true"><use href="/static/icons.6eec2e95bede.svg#solid--graduation-cap"/></svg></span>Python Tutorials&nbsp;→<br><small class="text-secondary">In-depth articles and video courses</small></a>



<a class="dropdown-item " href="/learning-paths/" style="color: #ffc873; line-height: 110%;"><span class="icon baseline mr-1" aria-hidden="true"><svg aria-hidden="true"><use href="/static/icons.6eec2e95bede.svg#@learning-path"/></svg></span>Learning Paths&nbsp;→<br><small class="text-secondary">Guided study plans for accelerated learning</small></a>



<a class="dropdown-item " href="/quizzes/" style="color: #abe0e5; line-height: 110%;"><span class="icon baseline mr-1" aria-hidden="true"><svg aria-hidden="true"><use href="/static/icons.6eec2e95bede.svg#@quiz"/></svg></span>Quizzes&nbsp;→<br><small class="text-secondary">Check your learning progress</small></a>



<a class="dropdown-item " href="/tutorials/all/" style="color: #ccc; line-height: 110%;"><span class="icon baseline mr-1" aria-hidden="true"><svg aria-hidden="true"><use href="/static/icons.6eec2e95bede.svg#@category"/></svg></span>Browse Topics&nbsp;→<br><small class="text-secondary">Focus on a specific area or skill level</small></a>



<a class="dropdown-item " href="/community/" style="color: #e5c6ab; line-height: 110%;"><span class="icon baseline mr-1" aria-hidden="true"><svg aria-hidden="true"><use href="/static/icons.6eec2e95bede.svg#solid--message-smile"/></svg></span>Community Chat&nbsp;→<br><small class="text-secondary">Learn with other Pythonistas</small></a>



<a class="dropdown-item " href="/office-hours/" style="color: #e5c6ab; line-height: 110%;"><span class="icon baseline mr-1" aria-hidden="true"><svg aria-hidden="true"><use href="/static/icons.6eec2e95bede.svg#solid--users"/></svg></span>Office Hours&nbsp;→<br><small class="text-secondary">Live Q&A calls with Python experts</small></a>



<a class="dropdown-item " href="/podcasts/rpp/" style="color: #b8abe5; line-height: 110%;"><span class="icon baseline mr-1" aria-hidden="true"><svg aria-hidden="true"><use href="/static/icons.6eec2e95bede.svg#@podcast"/></svg></span>Podcast&nbsp;→<br><small class="text-secondary">Hear what’s new in the world of Python</small></a>



<a class="dropdown-item " href="/products/books/" style="color: #abe5b1; line-height: 110%;"><span class="icon baseline mr-1" aria-hidden="true"><svg aria-hidden="true"><use href="/static/icons.6eec2e95bede.svg#solid--book-heart"/></svg></span>Books&nbsp;→<br><small class="text-secondary">Round out your knowledge and learn offline</small></a>



<a class="dropdown-item " href="/ref/" style="color: #abe0e5; line-height: 110%;"><span class="icon baseline mr-1" aria-hidden="true"><svg aria-hidden="true"><use href="/static/icons.6eec2e95bede.svg#@reference"/></svg></span>Reference&nbsp;→<br><small class="text-secondary">Concise definitions for common Python terms</small></a>




<a class="dropdown-item " href="/mentor/" style="color: #ffc873; line-height: 110%;"><span class="icon baseline mr-1" aria-hidden="true"><svg aria-hidden="true"><use href="/static/icons.6eec2e95bede.svg#@code-mentor"/></svg></span>Code Mentor&nbsp;→<span class="float-right badge badge-pill badge-indigo">Beta</span><br><small class="text-secondary">Personalized code assistance &amp; learning tools</small></a>






<a class="dropdown-item border-top" href="/account/join/" style="color: #ffc107; line-height: 110%;"><span class="icon baseline mr-1" aria-hidden="true"><svg aria-hidden="true"><use href="/static/icons.6eec2e95bede.svg#solid--star"/></svg></span>Unlock All Content&nbsp;→</a>



          </div>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link rounded dropdown-toggle" href="#" id="navbarDropdownMore" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            More
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMore">
            <a class="dropdown-item" href="/learner-stories/">Learner Stories</a>
            <a class="dropdown-item" href="/newsletter/">Python Newsletter</a>
            <a class="dropdown-item" href="https://www.pythonjobshq.com" target="_blank">Python Job Board</a>
            <a class="dropdown-item" href="/team/">Meet the Team</a>
            <a class="dropdown-item" href="/write-for-us/">Become a Tutorial Writer</a>
            <a class="dropdown-item" href="/become-an-instructor/">Become a Video Instructor</a>
          </div>
        </li>

      </ul>


      <div class="d-block d-lg-none">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link rounded" href="/search" title="Search"><span class="icon baseline" aria-hidden="true"><svg aria-hidden="true"><use href="/static/icons.6eec2e95bede.svg#v4--search"/></svg></span> Search</a>
          </li>
        </ul>
      </div>

      <div class="d-none d-lg-flex align-items-center mr-2 flex-fill">
        <form class="form-inline w-100 position-relative" action="/search" method="GET">
          <a class="js-search-form-submit position-absolute" href="/search" title="Search" aria-hidden="true" tabindex="-1"><span class="icon baseline text-muted pl-2" aria-hidden="true"><svg aria-hidden="true"><use href="/static/icons.6eec2e95bede.svg#v4--search"/></svg></span></a>
          <input class="search-autocomplete search-field form-control form-control-md mr-sm-1 mr-lg-2 w-100" style="padding-left: 2rem;" maxlength=50 type="search" placeholder="Search" aria-label="Search" aria-keyshortcuts="/ Control+J Meta+J" name="q" autocomplete="off">
          <span class="search-hotkey-indicator position-absolute px-2 border border-input text-input rounded small user-select-none" style="right: 1em;" title="Press / (forward slash) or Ctrl+J to open search" aria-hidden="true">/</span>
          <input type="hidden" name="_from" value="nav">
        </form>
      </div>


      <ul class="navbar-nav ml-auto">

          <li class="nav-item form-inline mr-2 my-2 ml-3 ml-lg-0">
            <a class="btn btn-sm btn-primary px-5 px-lg-3" href="/account/join/">Join</a>
          </li>



          <li class="nav-item">
            <a class="nav-link rounded mx-0 px-lg-2" href="/account/login/?next=%2F">Sign&#8209;In</a>
          </li>

      </ul>


    </div>

  </div>



</nav>



    <div class="container main-content">



  <div class="row">

  <div class="col-md-12 col-lg-8">
    <div class="row">
      <div class="col-12">
        <h1 class="mb-2 display-3">Real Python Tutorials</h1>
      </div>


      <div class="col-12 mb-3">
        <div class="card border-0">

          <a href="/courses/build-command-line-todo-app-typer/">
            <div class="embed-responsive embed-responsive-16by9">

                <img class="card-img-top m-0 p-0 embed-responsive-item rounded" style="object-fit: contain; background: #ff7e74;" src="https://files.realpython.com/media/Create-a-CLI-application-with-Typer_Watermarked.5fca92d22184.jpeg" alt="Build a Command-Line To-Do App With Python and Typer" width="1920" height="1080" srcset="/cdn-cgi/image/width=480,format=auto/https://files.realpython.com/media/Create-a-CLI-application-with-Typer_Watermarked.5fca92d22184.jpeg 480w, /cdn-cgi/image/width=640,format=auto/https://files.realpython.com/media/Create-a-CLI-application-with-Typer_Watermarked.5fca92d22184.jpeg 640w, /cdn-cgi/image/width=960,format=auto/https://files.realpython.com/media/Create-a-CLI-application-with-Typer_Watermarked.5fca92d22184.jpeg 960w, /cdn-cgi/image/width=1920,format=auto/https://files.realpython.com/media/Create-a-CLI-application-with-Typer_Watermarked.5fca92d22184.jpeg 1920w" sizes="(min-width: 1200px) 690px, (min-width: 1000px) 610px, (min-width: 780px) 690px, (min-width: 580px) 510px, calc(100vw - 30px)" >


                <div class="card-img-overlay d-flex align-items-center">
                  <div class="mx-auto">
                    <span class="text-light" style="opacity: 0.90;"><span class="icon baseline scale5x" aria-hidden="true"><svg aria-hidden="true"><use href="/static/icons.6eec2e95bede.svg#@play"/></svg></span></span>
                  </div>
                </div>


              <div class="shadow-sm p-0 bg-dark rounded-left border-left border-top border-bottom border-light text-center d-flex align-items-center justify-content-center" style="position:absolute; top:1em; right:0; width: 5em; height: 2em; ">
                <span class="text-light m-0 p-0">NEW</span>
              </div>

            </div>
          </a>

          <div class="card-body m-0 p-0 pt-3">
            <a href="/courses/build-command-line-todo-app-typer/">
              <h2 class="card-title h2 my-0 py-0">Building a Python Command-Line To-Do App With Typer</h2>
            </a>
            <p class="my-1">In this step-by-step video course, you&#x27;ll create a to-do application for your command line using Python and Typer. While you build this app, you&#x27;ll learn the basics of Typer, a modern and versatile library for building command-line interfaces (CLI).</p>
            <p class="card-text">
              <small class="text-muted">

                  <span class="mr-2">Feb 11, 2025</span>


                <span class="icon baseline ml-2" aria-hidden="true"><svg aria-hidden="true"><use href="/static/icons.6eec2e95bede.svg#@category"/></svg></span>


<a href="/tutorials/intermediate/" class="badge badge-light text-muted" data-previewable>intermediate</a>



<a href="/tutorials/projects/" class="badge badge-light text-muted" data-previewable>projects</a>



<a href="/tutorials/testing/" class="badge badge-light text-muted" data-previewable>testing</a>



<a href="/tutorials/tools/" class="badge badge-light text-muted" data-previewable>tools</a>


              </small>
            </p>
          </div>
        </div>
      </div>

    </div>
  </div>

  <div class="col-12 col-lg-4">
    <div class="row">
      <div class="col-12">





<div class="card mb-3 bg-secondary">
  <form class="card-body" action="/optins/process/" method="post">
    <div class="form-group">
      <p class="h5 text-muted text-center">— FREE Email Series —</p>
      <p class="h3 text-center">🐍 Python Tricks 💌</p>
      <p><img loading="lazy" class="img-fluid rounded" src="/static/pytrick-dict-merge.4201a0125a5e.png" width="738" height="490" alt="Python Tricks Dictionary Merge"></p>
    </div>
    <div class="form-group">
      <input type="hidden" name="csrfmiddlewaretoken" value="xE3W8InNzS7wSgyCw3OQuHb5MwD2TAhGfCVegbcTghNzP1KdcGcHQo1JeHZcW2EK">
      <input type="hidden" name="slug" value="static-python-tricks-sidebar">
      <input type="email" class="form-control form-control-md" name="email" placeholder="Email&hellip;" required>
    </div>
    <button type="submit" name="submit" class="btn btn-primary btn-md btn-block">Get Python Tricks »</button>
    <p class="mb-0 mt-2 text-muted text-center">🔒 No spam. Unsubscribe any time.</p>
  </form>
</div>


      </div>
      <div class="col-12">



<div class="sidebar-module sidebar-module-inset border">
  <a href="/tutorials/all/" class="badge badge-light text-muted"><span class="icon baseline mr-1" aria-hidden="true"><svg aria-hidden="true"><use href="/static/icons.6eec2e95bede.svg#@category"/></svg></span>Browse Topics</a>

  <a href="/learning-paths/" class="badge badge-light text-muted"><span class="icon baseline mr-1" aria-hidden="true"><svg aria-hidden="true"><use href="/static/icons.6eec2e95bede.svg#solid--map-location-dot"/></svg></span>Guided Learning Paths</a>

  <br>

  <a href="/search?level=basics" class="badge badge-light text-muted"><span class="icon baseline" aria-hidden="true"><svg aria-hidden="true"><use href="/static/icons.6eec2e95bede.svg#@level"/></svg></span> Basics</a>

  <a href="/search?level=intermediate" class="badge badge-light text-muted"><span class="icon baseline" aria-hidden="true"><svg aria-hidden="true"><use href="/static/icons.6eec2e95bede.svg#@level"/></svg></span><span class="icon baseline tight-left" aria-hidden="true"><svg aria-hidden="true"><use href="/static/icons.6eec2e95bede.svg#@level"/></svg></span> Intermediate</a>

  <a href="/search?level=advanced" class="badge badge-light text-muted"><span class="icon baseline" aria-hidden="true"><svg aria-hidden="true"><use href="/static/icons.6eec2e95bede.svg#@level"/></svg></span><span class="icon baseline tight-left" aria-hidden="true"><svg aria-hidden="true"><use href="/static/icons.6eec2e95bede.svg#@level"/></svg></span><span class="icon baseline tight-left" aria-hidden="true"><svg aria-hidden="true"><use href="/static/icons.6eec2e95bede.svg#@level"/></svg></span> Advanced</a>

  <hr class="my-2">










<a href="/tutorials/api/" class="badge badge-light text-muted" data-previewable>api</a>





<a href="/tutorials/best-practices/" class="badge badge-light text-muted" data-previewable>best-practices</a>





<a href="/tutorials/career/" class="badge badge-light text-muted" data-previewable>career</a>





<a href="/tutorials/community/" class="badge badge-light text-muted" data-previewable>community</a>





<a href="/tutorials/databases/" class="badge badge-light text-muted" data-previewable>databases</a>





<a href="/tutorials/data-science/" class="badge badge-light text-muted" data-previewable>data-science</a>





<a href="/tutorials/data-structures/" class="badge badge-light text-muted" data-previewable>data-structures</a>





<a href="/tutorials/data-viz/" class="badge badge-light text-muted" data-previewable>data-viz</a>





<a href="/tutorials/devops/" class="badge badge-light text-muted" data-previewable>devops</a>





<a href="/tutorials/django/" class="badge badge-light text-muted" data-previewable>django</a>





<a href="/tutorials/docker/" class="badge badge-light text-muted" data-previewable>docker</a>





<a href="/tutorials/editors/" class="badge badge-light text-muted" data-previewable>editors</a>





<a href="/tutorials/flask/" class="badge badge-light text-muted" data-previewable>flask</a>





<a href="/tutorials/front-end/" class="badge badge-light text-muted" data-previewable>front-end</a>





<a href="/tutorials/gamedev/" class="badge badge-light text-muted" data-previewable>gamedev</a>





<a href="/tutorials/gui/" class="badge badge-light text-muted" data-previewable>gui</a>





<a href="/tutorials/machine-learning/" class="badge badge-light text-muted" data-previewable>machine-learning</a>





<a href="/tutorials/numpy/" class="badge badge-light text-muted" data-previewable>numpy</a>





<a href="/tutorials/projects/" class="badge badge-light text-muted" data-previewable>projects</a>





<a href="/tutorials/python/" class="badge badge-light text-muted" data-previewable>python</a>





<a href="/tutorials/testing/" class="badge badge-light text-muted" data-previewable>testing</a>





<a href="/tutorials/tools/" class="badge badge-light text-muted" data-previewable>tools</a>





<a href="/tutorials/web-dev/" class="badge badge-light text-muted" data-previewable>web-dev</a>





<a href="/tutorials/web-scraping/" class="badge badge-light text-muted" data-previewable>web-scraping</a>



</div>


      </div>
    </div>
  </div>

  <div class="col-12 mt-4">
    <div class="d-flex justify-content-between align-items-center w-100 mt-0 mb-2">
  <h2 class="my-0">Explore Real Python</h2>

</div>


<div class="card-deck mb-3 pl-md-3 pl-sm-3">


<div class="card bg-dark border-0 ml-0 mr-md-3">
  <div class="card-body text-center highlight-hover-dark rounded">

In [7]:
print(type(response.text))

<class 'str'>

In [8]:
html_doc=response.text

In [9]:
soup=BeautifulSoup(html_doc,"html.parser")

In [10]:
titles=soup.find_all("h2",class_="card-title")
titles

[<h2 class="card-title h2 my-0 py-0">Building a Python Command-Line To-Do App With Typer</h2>,
 <h2 class="card-title h4 my-0 py-0">How to Join Strings in Python</h2>,
 <h2 class="card-title h4 my-0 py-0">How to Split a String in Python</h2>,
 <h2 class="card-title h4 my-0 py-0">NumPy Techniques and Practical Examples</h2>,
 <h2 class="card-title h4 my-0 py-0">Python for Loops: The Pythonic Way</h2>,
 <h2 class="card-title h4 my-0 py-0">Build a Quiz Application With Python</h2>,
 <h2 class="card-title h4 my-0 py-0">Top Python Game Engines</h2>,
 <h2 class="card-title h4 my-0 py-0">Develop Data Visualization Interfaces in Python With Dash</h2>,
 <h2 class="card-title h4 my-0 py-0">Build a Dice-Rolling Application With Python</h2>,
 <h2 class="card-title h4 my-0 py-0">Python &amp; APIs: A Winning Combo for Reading Public Data</h2>,
 <h2 class="card-title h4 my-0 py-0">A Guide to Modern Python String Formatting Tools</h2>,
 <h2 class="card-title h4 my-0 py-0">Providing Multiple Constructors in Your Python Classes</h2>,
 <h2 class="card-title h4 my-0 py-0">Build a Tic-Tac-Toe Game With Python and Tkinter</h2>,
 <h2 class="card-title h4 my-0 py-0">Natural Language Processing With spaCy in Python</h2>,
 <h2 class="card-title h4 my-0 py-0">Split Your Dataset With scikit-learn's train_test_split()</h2>,
 <h2 class="card-title h4 my-0 py-0">Creating a Scalable Flask Web Application From Scratch</h2>,
 <h2 class="card-title h4 my-0 py-0">How to Split a Python List or Iterable Into Chunks</h2>,
 <h2 class="card-title h4 my-0 py-0">Python's "in" and "not in" Operators: Check for Membership</h2>,
 <h2 class="card-title h4 my-0 py-0">Python Folium: Create Web Maps From Your Data</h2>]

In [11]:
"""data=[]
for i in titles:
    #print(i.text)
    data.append(i.text)
data"""
data=[i.text for i in titles]
data

['Building a Python Command-Line To-Do App With Typer',
 'How to Join Strings in Python',
 'How to Split a String in Python',
 'NumPy Techniques and Practical Examples',
 'Python for Loops: The Pythonic Way',
 'Build a Quiz Application With Python',
 'Top Python Game Engines',
 'Develop Data Visualization Interfaces in Python With Dash',
 'Build a Dice-Rolling Application With Python',
 'Python & APIs: A Winning Combo for Reading Public Data',
 'A Guide to Modern Python String Formatting Tools',
 'Providing Multiple Constructors in Your Python Classes',
 'Build a Tic-Tac-Toe Game With Python and Tkinter',
 'Natural Language Processing With spaCy in Python',
 "Split Your Dataset With scikit-learn's train_test_split()",
 'Creating a Scalable Flask Web Application From Scratch',
 'How to Split a Python List or Iterable Into Chunks',
 'Python\'s "in" and "not in" Operators: Check for Membership',
 'Python Folium: Create Web Maps From Your Data']

In [12]:
DIC ={"CARD TITLES":data}
DIC

{'CARD TITLES': ['Building a Python Command-Line To-Do App With Typer',
  'How to Join Strings in Python',
  'How to Split a String in Python',
  'NumPy Techniques and Practical Examples',
  'Python for Loops: The Pythonic Way',
  'Build a Quiz Application With Python',
  'Top Python Game Engines',
  'Develop Data Visualization Interfaces in Python With Dash',
  'Build a Dice-Rolling Application With Python',
  'Python & APIs: A Winning Combo for Reading Public Data',
  'A Guide to Modern Python String Formatting Tools',
  'Providing Multiple Constructors in Your Python Classes',
  'Build a Tic-Tac-Toe Game With Python and Tkinter',
  'Natural Language Processing With spaCy in Python',
  "Split Your Dataset With scikit-learn's train_test_split()",
  'Creating a Scalable Flask Web Application From Scratch',
  'How to Split a Python List or Iterable Into Chunks',
  'Python\'s "in" and "not in" Operators: Check for Membership',
  'Python Folium: Create Web Maps From Your Data']}

In [13]:
import pandas as x
df = x.DataFrame(DIC)
df

                                          CARD TITLES
0   Building a Python Command-Line To-Do App With ...
1                       How to Join Strings in Python
2                     How to Split a String in Python
3             NumPy Techniques and Practical Examples
4                  Python for Loops: The Pythonic Way
5                Build a Quiz Application With Python
6                             Top Python Game Engines
7   Develop Data Visualization Interfaces in Pytho...
8        Build a Dice-Rolling Application With Python
9   Python & APIs: A Winning Combo for Reading Pub...
10   A Guide to Modern Python String Formatting Tools
11  Providing Multiple Constructors in Your Python...
12   Build a Tic-Tac-Toe Game With Python and Tkinter
13   Natural Language Processing With spaCy in Python
14  Split Your Dataset With scikit-learn's train_t...
15  Creating a Scalable Flask Web Application From...
16  How to Split a Python List or Iterable Into Ch...
17  Python's "in" and "not in" Operators: Check fo...
18      Python Folium: Create Web Maps From Your Data

In [14]:
df.to_csv("CARD_TITLES.csv")

In [15]:
df.index=range(1,len(df)+1)
df

                                          CARD TITLES
1   Building a Python Command-Line To-Do App With ...
2                       How to Join Strings in Python
3                     How to Split a String in Python
4             NumPy Techniques and Practical Examples
5                  Python for Loops: The Pythonic Way
6                Build a Quiz Application With Python
7                             Top Python Game Engines
8   Develop Data Visualization Interfaces in Pytho...
9        Build a Dice-Rolling Application With Python
10  Python & APIs: A Winning Combo for Reading Pub...
11   A Guide to Modern Python String Formatting Tools
12  Providing Multiple Constructors in Your Python...
13   Build a Tic-Tac-Toe Game With Python and Tkinter
14   Natural Language Processing With spaCy in Python
15  Split Your Dataset With scikit-learn's train_t...
16  Creating a Scalable Flask Web Application From...
17  How to Split a Python List or Iterable Into Ch...
18  Python's "in" and "not in" Operators: Check fo...
19      Python Folium: Create Web Maps From Your Data

In [16]:
response=requests.get(url="https://visaguide.world/asia/")

In [17]:
print(response.text)

<!DOCTYPE html>
<html lang="en-US">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="profile" href="https://gmpg.org/xfn/11">
	<meta name='robots' content='index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1' />
	<style>img:is([sizes="auto" i], [sizes^="auto," i]) { contain-intrinsic-size: 3000px 1500px }</style>

	<!-- This site is optimized with the Yoast SEO plugin v24.2 - https://yoast.com/wordpress/plugins/seo/ -->
	<title>List of Countries in Asia - VisaGuide.World</title><link rel="preload" data-rocket-preload as="image" href="https://visaguide.world/wp-content/uploads/2023/01/Visa-Guide-World.svg" fetchpriority="high"><link rel="preload" data-rocket-preload as="style" href="https://fonts.googleapis.com/css?family=Roboto%3A300%2C400%2C500&#038;display=swap" /><link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto%3A300%2C400%2C500&#038;display=swap" media="print" onload="this.media='all'" /><noscript><link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto%3A300%2C400%2C500&#038;display=swap" /></noscript>
	<link rel="canonical" href="https://visaguide.world/asia/" />
	<meta name="twitter:card" content="summary_large_image" />
	<meta name="twitter:title" content="List of Countries in Asia - VisaGuide.World" />
	<meta name="twitter:description" content="Getting a Visa to Visit Asian Countries To travel to Asian countries for tourism or business purposes, you may need a visa, e-visa, visa-on-arrival, or travel authorization. Visa requirements depend on your nationality as well as the country of destination. You can check out the visa policies of Asian countries below: Armenia Bahrain Brunei Cambodia [&hellip;]" />
	<meta name="twitter:label1" content="Est. reading time" />
	<meta name="twitter:data1" content="6 minutes" />
	<script type="application/ld+json" class="yoast-schema-graph">{"@context":"https://schema.org","@graph":[{"@type":"WebPage","@id":"https://visaguide.world/asia/","url":"https://visaguide.world/asia/","name":"List of Countries in Asia - VisaGuide.World","isPartOf":{"@id":"https://visaguide.world/#website"},"datePublished":"2017-11-07T09:10:15+00:00","dateModified":"2024-07-12T12:01:25+00:00","breadcrumb":{"@id":"https://visaguide.world/asia/#breadcrumb"},"inLanguage":"en-US","potentialAction":[{"@type":"ReadAction","target":["https://visaguide.world/asia/"]}]},{"@type":"BreadcrumbList","@id":"https://visaguide.world/asia/#breadcrumb","itemListElement":[{"@type":"ListItem","position":1,"name":"VisaGuide","item":"https://visaguide.world/"},{"@type":"ListItem","position":2,"name":"Asia"}]},{"@type":"WebSite","@id":"https://visaguide.world/#website","url":"https://visaguide.world/","name":"VisaGuide.World","description":"","publisher":{"@id":"https://visaguide.world/#organization"},"potentialAction":[{"@type":"SearchAction","target":{"@type":"EntryPoint","urlTemplate":"https://visaguide.world/?s={search_term_string}"},"query-input":{"@type":"PropertyValueSpecification","valueRequired":true,"valueName":"search_term_string"}}],"inLanguage":"en-US"},{"@type":"Organization","@id":"https://visaguide.world/#organization","name":"VisaGuide.World","url":"https://visaguide.world/","logo":{"@type":"ImageObject","inLanguage":"en-US","@id":"https://visaguide.world/#/schema/logo/image/","url":"https://visaguide.world/wp-content/uploads/2023/01/Visa-Guide-World.svg","contentUrl":"https://visaguide.world/wp-content/uploads/2023/01/Visa-Guide-World.svg","caption":"VisaGuide.World"},"image":{"@id":"https://visaguide.world/#/schema/logo/image/"}}]}</script>
	<!-- / Yoast SEO plugin. -->


<link rel='dns-prefetch' href='//fonts.googleapis.com' />
<link href='https://fonts.gstatic.com' crossorigin rel='preconnect' />
<link rel='stylesheet' id='wp-block-library-css' href='https://visaguide.world/wp-includes/css/dist/block-library/style.min.css?ver=4b9a1cab33353d87cce7b370bba32919' media='all' />
<link rel='stylesheet' id='astra-theme-css-css' href='https://visaguide.world/wp-content/themes/astra/assets/css/minified/main.min.css?ver=4.8.10' media='all' />
<style id='astra-theme-css-inline-css'>

In [18]:
print(type(response.text))

<class 'str'>

In [19]:
html_doc=response.text

In [20]:
soup=BeautifulSoup(html_doc,"html.parser")

In [21]:
table=soup.find_all("table")

In [22]:
headings=table[1].find_all("th")
headings

[<th>Country</th>,
 <th>Capital</th>,
 <th>Area km2</th>,
 <th>Population (2021)</th>]

In [23]:
rows=table[1].find_all("td")
rows

[<td>Afghanistan</td>,
 <td>Kabul</td>,
 <td>652,864</td>,
 <td>39,835,428</td>,
 <td>Armenia</td>,
 <td>Yerevan</td>,
 <td>29,743</td>,
 <td>2,968,127</td>,
 <td>Azerbaijan</td>,
 <td>Baku</td>,
 <td>86,600</td>,
 <td>10,223,342</td>,
 <td>Bahrain</td>,
 <td>Manama</td>,
 <td>760</td>,
 <td>1,748,296</td>,
 <td>Bangladesh</td>,
 <td>Dhaka</td>,
 <td>147,570</td>,
 <td>166,303,498</td>,
 <td>Bhutan</td>,
 <td>Thimphu</td>,
 <td>38,394</td>,
 <td>779,898</td>,
 <td>Brunei</td>,
 <td>Bandar Seri Begawan</td>,
 <td>5,765</td>,
 <td>441,532</td>,
 <td>Cambodia</td>,
 <td>Phnom Penh</td>,
 <td>181,035</td>,
 <td>16,946,438</td>,
 <td>China (PRC)</td>,
 <td>Beijing</td>,
 <td>9,596,961</td>,
 <td>1,444,216,107</td>,
 <td>East Timor</td>,
 <td>Dili</td>,
 <td>14,874</td>,
 <td>1,343,873</td>,
 <td>Georgia</td>,
 <td>Tbilisi</td>,
 <td>69,700</td>,
 <td>3,979,765</td>,
 <td>Hong Kong</td>,
 <td>City of Victoria</td>,
 <td>2,755</td>,
 <td>7,552,810</td>,
 <td>India</td>,
 <td>New Delhi</td>,
 <td>3,287,263</td>,
 <td>1,393,409,038</td>,
 <td>Indonesia</td>,
 <td>Jakarta</td>,
 <td>1,904,569</td>,
 <td>276,361,783</td>,
 <td>Iran</td>,
 <td>Tehran</td>,
 <td>1,648,195</td>,
 <td>85,028,759</td>,
 <td>Iraq</td>,
 <td>Baghdad</td>,
 <td>438,317</td>,
 <td>41,179,350</td>,
 <td>Israel</td>,
 <td>Jerusalem (disputed)</td>,
 <td>20,770</td>,
 <td>8,789,774</td>,
 <td>Japan</td>,
 <td>Tokyo</td>,
 <td>377,915</td>,
 <td>126,050,804</td>,
 <td>Jordan</td>,
 <td>Amman</td>,
 <td>89,342</td>,
 <td>10,269,021</td>,
 <td>Kazakhstan</td>,
 <td>Nur-Sultan</td>,
 <td>2,724,900</td>,
 <td>18,994,962</td>,
 <td>Kuwait</td>,
 <td>Kuwait City</td>,
 <td>17,818</td>,
 <td>4,328,550</td>,
 <td>Kyrgyzstan</td>,
 <td>Bishkek</td>,
 <td>199,951</td>,
 <td>6,628,356</td>,
 <td>Laos</td>,
 <td>Vientiane</td>,
 <td>236,800</td>,
 <td>7,379,358</td>,
 <td>Lebanon</td>,
 <td>Beirut</td>,
 <td>10,400</td>,
 <td>6,769,146</td>,
 <td>Macau</td>,
 <td>Macau</td>,
 <td>115</td>,
 <td>658,394</td>,
 <td>Malaysia</td>,
 <td>Kuala Lumpur</td>,
 <td>329,847</td>,
 <td>32,776,194</td>,
 <td>Maldives</td>,
 <td>Malé</td>,
 <td>298</td>,
 <td>543,617</td>,
 <td>Mongolia</td>,
 <td>Ulaanbaatar</td>,
 <td>1,564,116</td>,
 <td>3,329,289</td>,
 <td>Myanmar</td>,
 <td>Naypyidaw</td>,
 <td>676,578</td>,
 <td>54,806,012</td>,
 <td>Nepal</td>,
 <td>Kathmandu</td>,
 <td>147,181</td>,
 <td>29,674,920</td>,
 <td>North Korea</td>,
 <td>Pyongyang</td>,
 <td>120,538</td>,
 <td>25,887,041</td>,
 <td>Oman</td>,
 <td>Muscat</td>,
 <td>309,500</td>,
 <td>5,223,375</td>,
 <td>Pakistan</td>,
 <td>Islamabad</td>,
 <td>881,913</td>,
 <td>225,199,937</td>,
 <td>Palestine</td>,
 <td>Ramallah</td>,
 <td>6,220</td>,
 <td>5,222,748</td>,
 <td>Qatar</td>,
 <td>Doha</td>,
 <td>11,586</td>,
 <td>2,930,528</td>,
 <td>Russia</td>,
 <td>Moscow</td>,
 <td>17,098,242</td>,
 <td>145,734,038</td>,
 <td>Saudi Arabia</td>,
 <td>Riyadh</td>,
 <td>2,149,690</td>,
 <td>35,340,683</td>,
 <td>Singapore</td>,
 <td>Singapore</td>,
 <td>697</td>,
 <td>5,896,686</td>,
 <td>South Korea</td>,
 <td>Seoul</td>,
 <td>100,210</td>,
 <td>51,305,186</td>,
 <td>Sri Lanka</td>,
 <td>Sri Jayawardenepura Kotte</td>,
 <td>65,610</td>,
 <td>21,497,310</td>,
 <td>Syria</td>,
 <td>Damascus</td>,
 <td>185,180</td>,
 <td>18,275,702</td>,
 <td>Taiwan</td>,
 <td>Taipei</td>,
 <td>36,193</td>,
 <td>23,855,010</td>,
 <td>Tajikistan</td>,
 <td>Dushanbe</td>,
 <td>143,100</td>,
 <td>9,749,627</td>,
 <td>Thailand</td>,
 <td>Bangkok</td>,
 <td>513,120</td>,
 <td>69,950,850</td>,
 <td>The Philippines</td>,
 <td>Manila</td>,
 <td>343,448</td>,
 <td>111,046,913</td>,
 <td>Turkey</td>,
 <td>Ankara</td>,
 <td>783,562</td>,
 <td>85,042,738</td>,
 <td>Turkmenistan</td>,
 <td>Ashgabat</td>,
 <td>488,100</td>,
 <td>6,117,924</td>,
 <td>United Arab Emirates</td>,
 <td>Abu Dhabi</td>,
 <td>83,600</td>,
 <td>9,991,089</td>,
 <td>Uzbekistan</td>,
 <td>Tashkent</td>,
 <td>447,400</td>,
 <td>33,935,763</td>,
 <td>Vietnam</td>,
 <td>Hanoi</td>,
 <td>331,212</td>,
 <td>98,168,833</td>,
 <td>Yemen</td>,
 <td>Sana’a</td>,
 <td>527,968</td>,
 <td>30,490,640</td>]